spring:
  datasource:
    url: jdbc:h2:file:./db/vilomoyu.db
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    platform: h2

  h2:
    console:
      path: h2
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
